### ISSUE TITLE
main issue is verify sdk only supported swift 3.0 

### ISSUE THREAD

**Issue by ghafartanveer** [Nexmo/verify-ios-sdk#19] opened 2016-12-29 04:23 UTC
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by shams-ahmed** [comment] 2016-12-29 09:34
closing since it a dupe of #18

**Closed as completed by shams-ahmed** 2016-12-29 09:34 UTC
